# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Marvin Steinkellner
name: Marvin Steinkellner
description: >- # this means to ignore newlines
  "Personal portfolio of Marvin Steinkellner"
locale: en-US
url: "https://marvinsteinkellner.ch"

# Minimal Mistakes settings
minimal_mistakes_skin: "default" # "default", "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Author settings
author:
  name: "Marvin Steinkellner"
  avatar: "/assets/images/profile-pic.jpg"
  bio: "Electrical Engineer"
  location: "Zürich, Switzerland"
  links:
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/MarvStein"
    - label: "LinkedIn"
      icon: "fab fa-fw fa-linkedin"
      url: "https://www.linkedin.com/in/marvin-steinkellner/"

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes@4.27.3
# Outputting
permalink: /:categories/:title/
timezone: Europe/Zurich

include:
  - _pages

# Defaults
defaults:
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

# Hide the RSS feed link in the footer
atom_feed:
  hide: true

plugins:
  - jekyll-include-cache
